
exports = module.exports = techTree;

//we're writing the MAX level tech state here
//actual running tree will be much more sparse until quite late in the 'game'
techTree.techState = {
	Observatory:{
		range:0,
		magnification:0,
		resolutionSize:0
	},
	Housing:{
		SkyScraper:{	
			capacity:0,
			luxury:0,
			buildElements:{},
			turnJoules:0
		},
		Dome:{	
			capacity:0,
			luxury:0,
			buildElements:{},
			turnJoules:0
		},
		Subterranean:{	
			capacity:0,
			luxury:0,
			buildElements:{},
			turnJoules:0
		},
		Undersea:{	
			capacity:0,
			luxury:0,
			buildElements:{},
			turnJoules:0
		},
		FloatingCity:{	
			capacity:0,
			luxury:0,
			buildElements:{},
			turnJoules:0
		}
	},
	SpaceStation:{
		Science:{
			maxShipCells:0,
			researchUnits:0,
			turnJoules:0,
			buildElements:{}
		},
		Energy:{
			maxShipCells:0,
			turnJoules:0,
			buildElements:{},
			joulesOutput:0
		},
		Military:{
			maxShipCells:0,
			turnJoules:0,
			buildElements:{},
			numFighterBays:0
		}
	},
	Orbital:{
		turnJoules:0,
		buildElements:{},
		maxCells:0
	},
	Warehouse:{
		turnJoules:0,
		buildElements:{},
		massLimit:0
	},
	Manufacturing:{
		turnJoules:0,
		buildElements:{},
		prductionUnits:0
	},
	University:{
		turnJoules:0,
		buildElements:{},
		researchUnits:0
	},
	EnergyPlant:{
		Hydrocarbon:{
			buildElements:{},
			turnElements:{},
			outputJoules:0,
			outputChemicals:{}
		},
		Fission:{
			buildElements:{},
			turnElements:{},
			outputJoules:0,
			outputChemicals:{}
		},
		Fusion:{
			buildElements:{},
			turnElements:{},
			outputJoules:{},
			outputChemicals:{}
		},
		Solar:{
			buildElements:{},
			outputJoules:{},
			efficiency:0
		},
		ForceFusion:{
			buildElements:{},
			turnElements:{},
			turnJoules:0,
			outputJoules:0,
			outputChemicals:{}
		},
		ForceAntimatter:{
			buildElements:{},
			turnElements:{},
			turnJoules:0,
			outputJoules:0
		},
		MatterConversion:{
			buildElements:{},
			turnElements:{},
			turnJoules:0,
			outputJoules:0
		},
		ZeroPoint:{
			buildElements:{},
			turnJoules:0,
			outputJoules:0
		},
		BraneExtraction:{
			buildElements:{},
			turnElements:{},
			turnJoules:0,
			outputJoules:0
		}
	},
	Wonder:{
		Colossus:{
			buildElements:{},
			turnJoules:0,
			affectedAttributes:{}
		},
		Library:{
			buildElements:{},
			turnJoules:0,
			affectedAttributes:{}
		},
		AmusementPark:{
			buildElements:{},
			turnJoules:0,
			affectedAttributes:{}
		},
		Arena:{
			buildElements:{},
			turnJoules:0,
			affectedAttributes:{}
		},
		Monolith:{
			buildElements:{},
			turnJoules:0,
			affectedAttributes:{}
		},
		GiantHead:{
			buildElements:{},
			turnJoules:0,
			affectedAttributes:{}
		},
		Palace:{
			buildElements:{},
			turnJoules:0,
			affectedAttributes:{}
		},
		Museum:{
			buildElements:{},
			turnJoules:0,
			affectedAttributes:{}
		},
		WarMemorial:{
			buildElements:{},
			turnJoules:0,
			affectedAttributes:{}
		},
		WildlifePreserve:{
			buildElements:{},
			turnJoules:0,
			affectedAttributes:{}
		},
		
	},
	EmpireCapital:{
		buildElements:{},
		turnJoules:0,
		affectedAttributes:{}
	},
	AreaCapital:{
		buildElements:{},
		turnJoules:0,
		affectedAttributes:{}
	},
	Mine:{
		Solid:{
			buildElements:{},
			turnJoules:0,
			numElementsPerTurn:0,
			massPerTurn:0
		},
		Liquid:{
			buildElements:{},
			turnJoules:0,
			numElementsPerTurn:0,
			massPerTurn:0
		},
		Gas:{
			buildElements:{},
			turnJoules:0,
			numElementsPerTurn:0,
			massPerTurn:0
		},
		Plasma:{
			buildElements:{},
			turnJoules:0,
			numElementsPerTurn:0,
			massPerTurn:0
		}
	},
	Terraformer:{
		Bio:{
			buildElements:{},
			turnJoules:0,
			habitabilityUnitsPerTurn:0
		},
		Chemical:{
			buildElements:{},
			turnJoules:0,
			habitabilityUnitsPerTurn:0
		},
		Nuclear:{
			buildElements:{},
			turnJoules:0,
			habitabilityUnitsPerTurn:0
		},
		Force:{
			buildElements:{},
			turnJoules:0,
			habitabilityUnitsPerTurn:0
		}
	},
	SpaceDock:{
		buildElements:{},
		turnJoules:0
	},
	MilitaryBase:{
		buildElements:{},
		turnJoules:0
	},
	TrainingAcademy:{
		buildElements:{},
		turnJoules:0
	},
	Ship:{
		Hull:{
			probe:{
				grossMass:0,
				numShipCells:5,
				standardDeployment:{
					Drive:1,
					EnergySource:1,
					SciencePackage:1,
					Comms:1,
					FuelStorage:1
				}
			},
			scout:{
				grossMass:0,
				numShipCells:7,
				standardDeployment:{
					Drive:2,
					EnergySource:1,
					SciencePackage:1,
					Comms:!,
					FuelStorage:1,
					Cabin:1
				}
			},
			fighter:{
				grossMass:0,
				numShipCells:8,
				standardDeployment:{
					Drive:2,
					Comms:1,
					Weapons:1,
					EnergySource:1,
					SciencePackage:1,
					FuelStorage:1,
					Cabin:1
				}
			},
			escort:{
				grossMass:0,
				numShipCells:10,
				standardDeployment:{
					Drive:2,
					Weapons:2,
					Comms:1,
					EnergySource:1,
					SciencePackage:1,
					FuelStorage:1,
					Cabin:2
				}
			},
			frigate:{
				grossMass:0,
				numShipCells:20,
				standardDeployment:{
					Drive:3,
					Cargo:1,
					Weapons:7,
					EnergySource:2,
					SciencePackage:2,
					Storage:1,
					Cabin:1,
					Comms:1
				}
			},
			transport:{
				grossMass:0,
				numShipCells:0,
				standardDeployment:{
					SciencePackage:1,
					Comms:1,
					Weapons:1,
					Cargo:0,
					Drive:0,
					Cabin:0,
					function(numCargoUnits){
						var x=Math.floor(numCargoUnits/50)+1;
						this.Cargo = numCargoUnits;
						this.Drive += x;
						this.Cabin += x;
					}
				}
			},
			battleship:{
				grossMass:0,
				numShipCells:50,
				standardDeployment:{
					Drive:6,
					Cargo:2,
					Weapons:12,
					EnergySource:4,
					SciencePackage:2,
					Storage:2,
					Cabin:6,
					Comms:2	
				}
			},
			carrier:{
				grossMass:0,
				numShipCells:0,
				numFighterBays:0,
				//each fighter bay must be the size of a fighter
				standardDeployment:{

				}
			},
			megaship:{
				grossMass:0,
				numShipCells:1000
			},
			seedship:{
				grossMass:0,
				numShipCells:0
			}
		},
		Storage:{},
		Cabin:{},
		Drive:{
			Docking:{
				Size:0, //ship units
				turnJoules:0,
				buildElements:0,
				minSpeed:0,
				maxSpeed:0
			},
			Stellar:{
				Size:0, //ship units
				turnJoules:0,
				buildElements:0,
				minSpeed:0,
				maxSpeed:0
			},
			InterStellar:{
				Size:0, //ship units
				turnJoules:0,
				buildElements:0,
				minSpeed:0,
				maxSpeed:0
			},
			Galactic:{
				Size:0, //ship units
				turnJoules:0,
				buildElements:0,
				minSpeed:0,
				maxSpeed:0
			},
			InterGalactic:{
				Size:0, //ship units
				turnJoules:0,
				buildElements:0,
				minSpeed:0,
				maxSpeed:0
			}
		},
		Weapons:{
			Beam:{
				size:0, //ship units
				turnJoules:0,
				buildElements:0,
				damagePerSecond:0
			},
			Missile:{
				size:0, //ship units
				turnJoules:0,
				buildElements:0,
				damagePerSecond:0
			}	
		},
		EnergySource:{
			Fission:{
				size:0,
				buildElements:{},
				turnElements:{},
				turnJoules:0,
				outputJoules:0
			},
			Fusion:{
				size:0,
				buildElements:{},
				turnElements:{},
				turnJoules:0,
				outputJoules:0
			},
			ForceFusion:{
				size:0,
				buildElements:{},
				turnElements:{},
				turnJoules:0,
				outputJoules:0
			},
			ForceAntimatter:{
				size:0,
				buildElements:{},
				turnElements:{},
				turnJoules:0,
				outputJoules:0
			},
			ZeroPoint:{
				size:0,
				buildElements:{},
				turnElements:{},
				turnJoules:0,
				outputJoules:0
			},
			BraneExtraction:{
				size:0,
				buildElements:{},
				turnElements:{},
				turnJoules:0,
				outputJoules:0
			}
		},
		Shields:{
			size:0,
			damageUnits:0,
			rechargeRate:0,
			buildElements:{}
		},
		Armour:{
			size:0,
			damageUnits:0,
			buildElements:{}
		},
		SciencePackage:{
			EffectiveRange:0

		},
		Computer:{



		},
		CargoBay:{

		},
		Sensors:{

		},
		Comms:{

		}

	},
	Nanites:{
		Macro:{},
		Micro:{},
		Nano:{},
		Atmo:{}
	},
	Forcefields:{
		Level1:{},
		Level2:{},
		Level3:{},
		Level4:{},
		Level5:{}
	},
	QuantumShoebox:{
		Level1:{},
		Level2:{},
		Level3:{},
		Level4:{},
		Level5:{},
		LinkedShoebox:{},
		Ansible:{},
		Stargate:{}
	},



};


function techTree(civ) {
    this.civ = civ;
}
